version: '3.9'
services:
  xui:
    image: alireza7/x-ui2
    container_name: x-ui2
    volumes:
      - $PWD/db/:/etc/x-ui2/
      - $PWD/cert/:/root/cert/
    restart: unless-stopped
    network_mode: host
